export const plots = [
    {
        id: 'plot-1',
        title: 'Prime Residential Plot – Ollur Junction',
        location: 'Ollur',
        area: 'Thrissur City',
        purpose: 'residential',
        price: 38,
        size: 7,
        sizeUnit: 'cents',
        dimensions: '60ft × 50ft',
        roadAccess: '20ft road',
        landmark: '500m from NH-544',
        featured: true,
        images: [
            'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop',
        ],
        description: 'A premium residential plot situated at a prime location near Ollur Junction with excellent road connectivity. Surrounded by developed infrastructure, schools, hospitals, and shopping centres within 2km radius.',
        legalHighlights: ['Clear patta in seller\'s name', 'No encumbrances (EC verified)', 'Approved layout plan available', 'DTCP approved', 'Possession immediate'],
        nearbyPlaces: [
            { name: 'Ollur St. Thomas Church', type: 'landmark', distance: '0.3 km' },
            { name: 'PVS Memorial Hospital', type: 'hospital', distance: '1.2 km' },
            { name: 'Ollur Government School', type: 'school', distance: '0.8 km' },
            { name: 'National Highway NH-544', type: 'road', distance: '0.5 km' },
        ],
        postedDate: '2026-02-10',
        views: 342,
    },
    {
        id: 'plot-2',
        title: 'Commercial Corner Plot – Thrissur Round',
        location: 'Thrissur City',
        area: 'Thrissur City',
        purpose: 'commercial',
        price: 95,
        size: 4,
        sizeUnit: 'cents',
        dimensions: '40ft × 45ft',
        roadAccess: 'Main road access (40ft)',
        landmark: 'Opposite Thrissur Round',
        featured: true,
        images: [
            'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=800&auto=format&fit=crop',
        ],
        description: 'High-visibility commercial plot right opposite Thrissur Round. Ideal for showrooms, offices, or retail outlets. One of the few remaining commercial properties at this premium location with unmatched footfall.',
        legalHighlights: ['Clear land record verified', 'Municipal approved for commercial use', 'Encumbrance free (30 year EC)', 'Immediate registration possible'],
        nearbyPlaces: [
            { name: 'Thrissur Round', type: 'landmark', distance: '0 km' },
            { name: 'Vadakkumnathan Temple', type: 'temple', distance: '0.4 km' },
            { name: 'SBI Main Branch', type: 'bank', distance: '0.2 km' },
        ],
        postedDate: '2026-02-08',
        views: 561,
    },
    {
        id: 'plot-3',
        title: 'Investment Land – Chalakudy Highway',
        location: 'Chalakudy',
        area: 'Chalakudy',
        purpose: 'investment',
        price: 22,
        size: 15,
        sizeUnit: 'cents',
        dimensions: 'Irregular – 120ft frontage',
        roadAccess: '30ft highway road',
        landmark: 'Chalakudy – Thrissur main route',
        featured: true,
        images: [
            'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1549517045-bc93de075e53?w=800&auto=format&fit=crop',
        ],
        description: 'Large investment plot along the Chalakudy – Thrissur highway corridor. Perfect for future commercial development or long-term land banking. The area is witnessing rapid appreciation with the upcoming bypass.',
        legalHighlights: ['Survey document available', 'Zero dispute history', 'Development potential – conversion possible', 'Clear title deed'],
        nearbyPlaces: [
            { name: 'Athirapally Junction', type: 'landmark', distance: '8 km' },
            { name: 'Chalakudy Bus Stand', type: 'transport', distance: '1.5 km' },
        ],
        postedDate: '2026-02-05',
        views: 218,
    },
    {
        id: 'plot-4',
        title: 'Residential Plot – Guruvayur Town',
        location: 'Guruvayur',
        area: 'Guruvayur',
        purpose: 'residential',
        price: 55,
        size: 5,
        sizeUnit: 'cents',
        dimensions: '50ft × 44ft',
        roadAccess: '15ft road',
        landmark: '1km from Guruvayur Temple',
        featured: false,
        images: [
            'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1516455207984-28b4d4c0a234?w=800&auto=format&fit=crop',
        ],
        description: 'Excellent residential plot in one of Kerala\'s most sacred and in-demand locations. Just 1 km from the world-famous Guruvayur Sri Krishna Temple. Strong rental and resale demand from pilgrims and devotees.',
        legalHighlights: ['Revenue document clear', 'Patta in seller name', 'EC checked for 30 years', 'Approved layout'],
        nearbyPlaces: [
            { name: 'Guruvayur Temple', type: 'temple', distance: '1 km' },
            { name: 'Guruvayur KSRTC Station', type: 'transport', distance: '0.5 km' },
        ],
        postedDate: '2026-02-01',
        views: 429,
    },
    {
        id: 'plot-5',
        title: 'Layout Plot – Irinjalakuda NH Side',
        location: 'Irinjalakuda',
        area: 'Irinjalakuda',
        purpose: 'residential',
        price: 28,
        size: 6,
        sizeUnit: 'cents',
        dimensions: '55ft × 48ft',
        roadAccess: '30ft main road',
        landmark: '200m from KSEB Office',
        featured: false,
        images: [
            'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop',
        ],
        description: 'Well-planned layout plot on the National Highway side at Irinjalakuda. Ready for construction with all utilities available. Close to engineering college, hospital and market.',
        legalHighlights: ['DTCP approved layout', 'Clear title', 'No tax arrears'],
        nearbyPlaces: [
            { name: 'Christ College Irinjalakuda', type: 'college', distance: '2 km' },
            { name: 'Irinjalakuda Railway Station', type: 'transport', distance: '0.8 km' },
        ],
        postedDate: '2026-01-25',
        views: 187,
    },
    {
        id: 'plot-6',
        title: 'Agricultural-Converted Land – Kunnamkulam',
        location: 'Kunnamkulam',
        area: 'Kunnamkulam',
        purpose: 'investment',
        price: 18,
        size: 24,
        sizeUnit: 'cents',
        dimensions: 'Irregular – large frontage',
        roadAccess: '20ft access road',
        landmark: 'Near Kunnamkulam Market',
        featured: false,
        images: [
            'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop',
        ],
        description: 'Large converted land parcel in Kunnamkulam with good frontage. Excellent for gated community development, warehousing, or long-term investment. Verified and dispute-free.',
        legalHighlights: ['Land conversion certificate available', 'Survey settled', 'Tax paid current'],
        nearbyPlaces: [
            { name: 'Kunnamkulam Town', type: 'landmark', distance: '0.5 km' },
        ],
        postedDate: '2026-01-20',
        views: 143,
    },
];

export const testimonials = [
    {
        id: 't1',
        name: 'Rajan Mathew',
        location: 'Thrissur',
        role: 'Business Owner',
        text: 'TCR Plots helped me find a perfect commercial site near Thrissur Round. The process was transparent and the team was extremely professional. No hidden surprises — just honest dealing.',
        rating: 5,
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop',
    },
    {
        id: 't2',
        name: 'Lekha Pillai',
        location: 'Dubai (NRI)',
        role: 'NRI Investor',
        text: 'As an NRI investor, I was nervous about buying land remotely. TCR Plots not only found me a great investment plot but also handled all documentation. Today I get excellent returns.',
        rating: 5,
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop',
    },
    {
        id: 't3',
        name: 'Sunil Kumar',
        location: 'Guruvayur',
        role: 'Home Builder',
        text: 'Found my dream residential plot through TCR Plots. Their legal team verified everything thoroughly. From site visit to registration, they were by my side at every step.',
        rating: 5,
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop',
    },
    {
        id: 't4',
        name: 'Priya Nair',
        location: 'Chalakudy',
        role: 'First-time Buyer',
        text: 'I had zero knowledge about buying land. TCR Plots educated me at every step — from understanding patta to registering the deed. I felt completely safe throughout.',
        rating: 5,
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop',
    },
    {
        id: 't5',
        name: 'Arun Varghese',
        location: 'Irinjalakuda',
        role: 'Chartered Accountant',
        text: 'As a CA, I know the risks of property deals. TCR Plots impressed me with their diligence — EC clearance, tax verification, survey documents. Everything was in perfect order.',
        rating: 5,
        avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&auto=format&fit=crop',
    },
];

export const blogPosts = [
    {
        id: 'b1',
        slug: 'why-invest-in-thrissur',
        title: 'Why Thrissur is Kerala\'s Best Land Investment Destination in 2026',
        excerpt: 'Land values in Thrissur have appreciated 8% annually for the past 5 years. Here\'s why smart investors are doubling down on the cultural capital of Kerala.',
        category: 'Investment',
        author: 'TCR Research Team',
        date: 'Feb 20, 2026',
        readTime: '6 min read',
        coverImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&auto=format&fit=crop',
        tags: ['Investment', 'Thrissur', 'Real Estate', 'Market Trends'],
    },
    {
        id: 'b2',
        slug: 'land-buying-guide-kerala',
        title: 'Complete Guide to Buying Land in Kerala: Documents, Process & Pitfalls',
        excerpt: 'Patta, EC, survey sketch, title deed — we break down every document you need and every red flag to watch out for when buying land in Kerala.',
        category: 'Legal Guide',
        author: 'Lakshmi Nair – Legal Head',
        date: 'Feb 14, 2026',
        readTime: '10 min read',
        coverImage: 'https://images.unsplash.com/photo-1507537297725-24a1c029d3ca?w=800&auto=format&fit=crop',
        tags: ['Legal', 'Documents', 'Guide', 'Kerala'],
    },
    {
        id: 'b3',
        slug: 'thrissur-pooram-land-culture',
        title: 'Thrissur Pooram & Why Cultural Capital Status Drives Real Estate Value',
        excerpt: 'Thrissur Pooram isn\'t just a festival — it\'s an economic engine. Tourism, footfall, and cultural prestige directly lift property values year after year.',
        category: 'Culture',
        author: 'Arun Menon',
        date: 'Feb 8, 2026',
        readTime: '5 min read',
        coverImage: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop',
        tags: ['Culture', 'Thrissur', 'Pooram', 'Investment'],
    },
];

export const stats = [
    { value: '1,200+', label: 'Plots Sold', icon: '🏆' },
    { value: '25+', label: 'Years of Trust', icon: '⭐' },
    { value: '1,000+', label: 'Happy Families', icon: '🏡' },
    { value: '10+', label: 'Areas Covered', icon: '📍' },
];

export const areas = [
    { name: 'Thrissur City', plots: 24, img: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&auto=format&fit=crop' },
    { name: 'Ollur', plots: 12, img: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&auto=format&fit=crop' },
    { name: 'Guruvayur', plots: 18, img: 'https://images.unsplash.com/photo-1516455207984-28b4d4c0a234?w=400&auto=format&fit=crop' },
    { name: 'Chalakudy', plots: 9, img: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&auto=format&fit=crop' },
    { name: 'Irinjalakuda', plots: 15, img: 'https://images.unsplash.com/photo-1549517045-bc93de075e53?w=400&auto=format&fit=crop' },
    { name: 'Kodungallur', plots: 7, img: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=400&auto=format&fit=crop' },
    { name: 'Kunnamkulam', plots: 11, img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&auto=format&fit=crop' },
    { name: 'Wadakkanchery', plots: 8, img: 'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=400&auto=format&fit=crop' },
];
